### ISSUE TITLE
how to install this tools, please teach me, im newbie

### ISSUE THREAD

**Issue by apambalik1337** [AlexC-ux/Arina-OSINT#1]

**Comment by AlexC-ux** [comment]
You did not specify your operating system.

If you have Windows (10 for example):
Go to https://github.com/AlexC-ux/Arina-OSINT/releases/
Look for Arina-OSINT-2.2, download win.zip archive, unzip into folder - done. Run the Arina.exe file to start the application.

If you have Linux (ubuntu for example):
Go to https://github.com/AlexC-ux/Arina-OSINT/releases/
Look for Arina-OSINT-2.1, download the linux.tar archive, 
Unpack the archive, open the console from the folder with the unpacked file, write in the console
sudo chmod +x Arina
Done. To run the application run the Arina file with the command ./arina
