### ISSUE TITLE
Console closes after all URLs are analyzed

### ISSUE THREAD

**Issue by jterpi** [AlexC-ux/Arina-OSINT#2]
I run it, and when it comes to the bottom of the URLs, the console closes. Id suggest adding a loop, so more usernames can be searched

**Comment by AlexC-ux** [comment]
What is your os?

**Comment by jterpi** [comment]
Win10

**Comment by AlexC-ux** [comment]
To prevent the console from closing, you need to run the program as follows:
1. open the folder with the file
2. click on the path at the top of the explorer window
3. write "cmd"
4. press enter
5. write "arina.exe"
6. press enter
7. The program should run

**Comment by jterpi** [comment]
Ok, now it works as intended
